# Originally forked from https://github.com/conda-forge/cudatoolkit-dev-feedstock
# Distributed under the BSD-3-Clause license
# Copyright (c) 2017, Continuum Analytics, Inc. All rights reserved.

{% set name = "cudatoolkit-dev" %}
{% set major_minor = major_minor_ver|default("12.2.0") %}

{% set cudavars = {
  "11.2.2": {
    "version": "11.2.2",
    "version_patch": {
      "linux64": "460.32.03",
      "ppc64le": "460.32.03",
    },
  },
   "11.4.4": {
    "version": "11.4.4",
    "version_patch": {
      "linux64": "470.82.01",
      "ppc64le": "470.82.01",
    },
  },
   "11.8.0": {
    "version": "11.8.0",
    "version_patch": {
      "linux64": "520.61.05",
      "ppc64le": "520.61.05",
    },
  },
   "12.2.0": {
    "version": "12.2.0",
    "version_patch": {
      "linux64": "535.54.03",
      "ppc64le": "535.54.03",
    },
  },

}
%}

{% set release = cudavars[major_minor]["version"] %}
{% set driver_version = cudavars[major_minor]["version_patch"]["linux64"] %}  # [linux64]
{% set driver_version = cudavars[major_minor]["version_patch"]["ppc64le"] %}  # [ppc64le]

package:
  name: {{ name|lower }}
  version: {{ release }}

source:
  path: ./

build:
  script: python build.py {{ release }} {{ driver_version }}  # [linux]
  number: 1

requirements:
  build:
    - python
  host:
    - wget  # [linux]
  run:
    - python
    - wget
test:
  requires:
    - numba <0.57
    - wget  # [linux]
    - {{ compiler('c') }}

about:
  home: "https://developer.nvidia.com"
  license: LicenseRef-NVIDIA-End-User-License-Agreement
  license_url: https://docs.nvidia.com/cuda/eula/index.html
  summary: "Develop, Optimize and Deploy GPU-accelerated Apps"
  description: |
    The NVIDIA CUDA Toolkit provides a development environment for creating
    high performance GPU-accelerated applications. With the CUDA Toolkit,
    you can develop, optimize and deploy your applications on GPU-accelerated
    embedded systems, desktop workstations, enterprise data centers,
    cloud-based platforms and HPC supercomputers. The toolkit includes
    GPU-accelerated libraries, debugging and optimization tools,
    a C/C++ compiler and a runtime library to deploy your application.
    This package consists of a post-install script that downloads and
    installs the full cuda toolkit(compiler, libraries, with the exception of cuda drivers).
  doc_url: https://developer.nvidia.com/cuda-toolkit
  dev_url: https://developer.nvidia.com/cuda-toolkit

extra:
  recipe-maintainers:
    - open-ce/open-ce-dev-team
